[package]
name = "project-ankos"
version = "0.2.0"
authors = ["Catherine Odo"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.1"
specs = "0.16.1"
specs-derive = "0.4.1"